// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2hHdz8fse7fMJP8ygu05LtPUDbAqPKVQ',
    appId: '1:604239799472:web:c1eb4d25703e47f6c88775',
    messagingSenderId: '604239799472',
    projectId: 'dispo-des-bros',
    authDomain: 'dispo-des-bros.firebaseapp.com',
    databaseURL: 'https://dispo-des-bros-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dispo-des-bros.firebasestorage.app',
    measurementId: 'G-PMCN0VD8DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ubAKQWDIPbuNicFleF4WFt1pxr8DDaQ',
    appId: '1:604239799472:android:7162ed4aeaae3665c88775',
    messagingSenderId: '604239799472',
    projectId: 'dispo-des-bros',
    databaseURL: 'https://dispo-des-bros-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dispo-des-bros.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6dGGjHYS-VSplsiJFuF0Ujfh5lMACOjc',
    appId: '1:604239799472:ios:4ee070276880550dc88775',
    messagingSenderId: '604239799472',
    projectId: 'dispo-des-bros',
    databaseURL: 'https://dispo-des-bros-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dispo-des-bros.firebasestorage.app',
    iosBundleId: 'com.example.dndAvailabilityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6dGGjHYS-VSplsiJFuF0Ujfh5lMACOjc',
    appId: '1:604239799472:ios:4ee070276880550dc88775',
    messagingSenderId: '604239799472',
    projectId: 'dispo-des-bros',
    databaseURL: 'https://dispo-des-bros-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dispo-des-bros.firebasestorage.app',
    iosBundleId: 'com.example.dndAvailabilityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2hHdz8fse7fMJP8ygu05LtPUDbAqPKVQ',
    appId: '1:604239799472:web:49e8259a35b1e098c88775',
    messagingSenderId: '604239799472',
    projectId: 'dispo-des-bros',
    authDomain: 'dispo-des-bros.firebaseapp.com',
    databaseURL: 'https://dispo-des-bros-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dispo-des-bros.firebasestorage.app',
    measurementId: 'G-XDPFTB0BLT',
  );
}
