name: Deploy Flutter Web to cojay77.github.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Flutter project
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --base-href=/

      - name: Copy service worker to build output
        run: cp web/firebase-messaging-sw.js build/web/firebase-messaging-sw.js

      - name: Deploy to cojay77.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: Cojay77/cojay77.github.io
          publish_branch: main
          publish_dir: build/web
          personal_token: ${{ secrets.TARGET_REPO_TOKEN }}
